### ISSUE TITLE
Won't detect joy-cons

### ISSUE THREAD

**Issue by GiovanniJOJO** [sarossilli/Musical-Joycons#7]
So, my joy-cons are paired vai bluetooth, however, when I run the latest windows 0,2,0 version, it says "Warning: Joycons not found. Make sure they are paired"

**Comment by GiovanniJOJO** [comment]
via*

**Comment by sarossilli** [comment]
Are the joycons 'connected'?
If the Bluetooth page says the joycons are ['Paired'](https://imgur.com/a/Wh3WQBg) then they arent connected
Try removing the joycons and re-connecting to them. This should make the joycons 'connected'

**Comment by GiovanniJOJO** [comment]
I did it.  I disconnected and reconnected. The joy-cons lights were even blinking but it didn't work

**Comment by sarossilli** [comment]
Huh, do you mind sending a screenshot of your Bluetooth settings on windows?

**Comment by GiovanniJOJO** [comment]
Hey sorry for the delay. I had lots of assignments to do yesterday and today i woke up very late. Anyway, there is the screenshot of my bluetooth settings. Note that I just disconect and connected the bluetooths again and the joy cons lights are blinking, however, the program still won't recognize my joy- cons. Ah, and my windows is in portuguese, just in case you need it.
![image](https://user-images.githubusercontent.com/81764169/113444626-a6708180-93ca-11eb-96da-bc65c8b8b16b.png)

**Comment by sarossilli** [comment]
Yeah, this seems to be an issue. Ill look into it this weekend. Sorry about that.

**Comment by GiovanniJOJO** [comment]
Ok. Thanks so much bro. I really appreciate your work. I am very excited to rickroll my sis. This is gonna be my late april fools prank lol. Thank you!

**Comment by GiovanniJOJO** [comment]
Any news on that buddy? No pressure.

**Comment by sarossilli** [comment]
I think I know the issue and Ill try to send you a fixed copy to try today.

**Comment by GiovanniJOJO** [comment]
OK buddy thanks so much!

**Comment by sarossilli** [comment]
Could you try running this version of the software?
[BugTest.zip](https://github.com/sarossilli/Musical-Joycons/files/6261059/BugTest.zip)

**Comment by sarossilli** [comment]
Also, were those joycons originals that came with the switch? I'm wondering if new joycons have a new vendor ID and the program is using the old vendor id

**Comment by GiovanniJOJO** [comment]
Gonna try this new version. I am using the original joycons that came with the switch. It is the v2 switch, the one with better battery and the red box.

**Comment by GiovanniJOJO** [comment]
It still didn't recognize my joy cons. I don't know if it matters, but when I connected them, they were recognized as different bluetooth devices. The left was recognized as a controller, and the right one as mouse or keyboard. When windows finished setting the joycons, both of them were displayed as mouse or keyboard in bluetooth settings. Anyway, thanks so much for spending your time trying to help me. Thank you!
![image](https://user-images.githubusercontent.com/81764169/113696191-0fe0e080-96a8-11eb-8f39-21b28fdb6a8e.png)

**Comment by sarossilli** [comment]
I'm sorry for having you do all this work. Can you try this version. It should output all the devices it finds and some data about them so that I can see if there is a different device ID that I didn't know about.

Also, I removed the part that quits the program if there are no joycons. You can see if it will work after I removed that check.

[BugTest.zip](https://github.com/sarossilli/Musical-Joycons/files/6265388/BugTest.zip)

**Comment by GiovanniJOJO** [comment]
Still did not work. Maybe it is some problem with bluetooth that is on my laptop? I am not really sure as I can still use BetterJoyForCemu without any problems. Note that the locate funcion on Better Joy makes my controle rumble. Anyway, thanks again!!!
![image](https://user-images.githubusercontent.com/81764169/113734830-0d937c00-96d2-11eb-8ceb-3a11189355d9.png)
![image](https://user-images.githubusercontent.com/81764169/113735561-bb068f80-96d2-11eb-8ede-359696f7c223.png)

**Comment by sarossilli** [comment]
Huh. Ill keep trying to figure it out. Sorry for the trouble.

**Comment by GiovanniJOJO** [comment]
No problem. i had an idea, however, I don't know if it is possible. As I said, there is this program called Better Joy For CEMU, and it works wonderfully with my joycons, even the rumble. Maybe you could somehow mod it so you can run midi files through it? Or who knows, see how it recognizes joy- cons and apply it to your program? I don't know. Maybe I am saying shit, I don't know. Anyway, in case you want to try somethin with it, there is the link: https://github.com/Davidobot/BetterJoy. As it is open source, I think you should have little to no problem looking into the code. Anyway, that is just a silly idea of mine. Thanks for the work!!!

**Comment by notme9239** [comment]
this solved my problem https://github.com/Davidobot/BetterJoy/wiki/FAQ-and-Problems the first thing served me

**Comment by GiovanniJOJO** [comment]
Thanks so much @ofes2200, worked like a miracle. LOL, gonna rickroll my sis. @sarossilli Thanks so much for your work. My enormous gratitude. Sorry for the trouble LMAO.
