### ISSUE TITLE
Crashing when I input track number. 

### ISSUE THREAD

**Issue by Usjdjdj** [sarossilli/Musical-Joycons#8]
If i put in the track number the program closes

**Comment by Usjdjdj** [comment]
![Uploading 16178051676722091048099015104103.jpg…]()

**Comment by Usjdjdj** [comment]
![IMG_20210407_162321.jpg](https://user-images.githubusercontent.com/82097674/113882762-ddc1a280-97bd-11eb-8bea-4a769c9c1566.jpg)

**Comment by Usjdjdj** [comment]
It sat at that screen for like 10 seconds and then disapeared

**Comment by sarossilli** [comment]
What did you enter into the track number?

**Comment by sarossilli** [comment]
You should only put a number in. For example, put '1' instead of 'track1'

**Comment by Usjdjdj** [comment]
I tried that and it didnt work

**Comment by Usjdjdj** [comment]
![IMG_20210407_165102.jpg](https://user-images.githubusercontent.com/82097674/113887175-90dfcb00-97c1-11eb-9585-4671e6f6323e.jpg)

**Comment by sarossilli** [comment]
Did it crash after entering that?

**Comment by schrammalama** [comment]
i have the same issue, i enter 1 it then asks for me to enter a track number to play on the right joycon a second time i then enter it again and it crashes

**Comment by sarossilli** [comment]
Have you tried imputing 2?
I think track 1 is an empty track on the overworld.mid file.
So it just plays nothing.

**Comment by Usjdjdj** [comment]
Tried it and didnt work i also tried my custom (midi) song it crashed too

**Comment by Usjdjdj** [comment]
Nvm it worked
